##**Ecommerce** **Data** **Analysis**

In [ ]:
#importing python libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

In [ ]:
#mount the drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#loading data set
order_report =pd.read_excel('/content/drive/MyDrive/assignment cointab/Company X - Order Report.xlsx')
pincode_mapping=pd.read_excel('/content/drive/MyDrive/assignment cointab/Company X - Pincode Zones.xlsx')
sku_master     =pd.read_excel('/content/drive/MyDrive/assignment cointab/Company X - SKU Master.xlsx')
courier_invoice=pd.read_excel('/content/drive/MyDrive/assignment cointab/Courier Company - Invoice.xlsx')
rate_card      =pd.read_excel('/content/drive/MyDrive/assignment cointab/Courier Company - Rates.xlsx')

In [ ]:
#overview of dataset
order_report

,ExternOrderNo,SKU,Order Qty,Payment Mode,Item Price(Per Qty.)
0,2001827036,8904223818706,1,COD,233
1,2001827036,8904223819093,1,COD,233
2,2001827036,8904223819109,1,COD,233
3,2001827036,8904223818430,1,COD,470
4,2001827036,8904223819277,1,COD,233
...,...,...,...,...,...
395,2001806229,8904223818942,1,COD,286
396,2001806229,8904223818850,1,COD,563
397,2001806226,8904223818850,2,COD,1125
398,2001806210,8904223816214,1,COD,402
399,2001806210,8904223818874,1,COD,922

In [ ]:
##overview of dataset
pincode_mapping

     Warehouse Pincode  Customer Pincode Zone
0               121003            507101    d
1               121003            486886    d
2               121003            532484    d
3               121003            143001    b
4               121003            515591    d
..                 ...               ...  ...
119             121003            325207    b
120             121003            303702    b
121             121003            313301    b
122             121003            173212    e
123             121003            302020    b

[124 rows x 3 columns]

In [ ]:
#overview of dataset
sku_master

              SKU  Weight (g)
0   8904223815682         210
1   8904223815859         165
2   8904223815866         113
3   8904223815873          65
4   8904223816214         120
..            ...         ...
61  8904223819505         210
62  8904223819499         210
63  8904223819512         210
64  8904223819543         300
65     SACHETS001          10

[66 rows x 2 columns]

In [ ]:
#overview of dataset
rate_card

,Zone,Weight Slabs,Forward Fixed Charge,Forward Additional Weight Slab Charge,RTO Fixed Charge,RTO Additional Weight Slab Charge
0,A,0.25,29.5,23.6,13.6,23.6
1,B,0.50,33.0,28.3,20.5,28.3
2,C,0.75,40.1,38.9,31.9,38.9
3,D,1.25,45.4,44.8,41.3,44.8
4,E,1.50,56.6,55.5,50.7,55.5

In [ ]:
#overview of dataset
courier_invoice

,AWB Code,Order ID,Charged Weight,Warehouse Pincode,Customer Pincode,Zone,Type of Shipment,Billing Amount (Rs.)
0,1091117222124,2001806232,1.30,121003,507101,d,Forward charges,140.0
1,1091117222194,2001806273,1.00,121003,486886,d,Forward charges,101.2
2,1091117222931,2001806408,2.50,121003,532484,d,Forward charges,224.6
3,1091117223244,2001806458,1.00,121003,143001,b,Forward charges,61.3
4,1091117229345,2001807012,0.15,121003,515591,d,Forward charges,45.4
...,...,...,...,...,...,...,...,...
119,1091118551656,2001812941,0.73,121003,325207,d,Forward charges,95.2
120,1091117614452,2001809383,0.50,121003,303702,d,Forward and RTO charges,86.7
121,1091120922803,2001820978,0.50,121003,313301,d,Forward charges,45.4
122,1091121844806,2001811475,0.50,121003,173212,b,Forward charges,47.0
123,1091121846136,2001811305,0.50,121003,302020,d,Forward charges,65.4

In [ ]:
#converting columns variable
rate_card.Zone=rate_card.Zone.apply(lambda x:x.lower())

In [ ]:
#Merge merged_order_data with sku_master to get product weights
order_data=pd.merge(courier_invoice,rate_card,on='Zone')

In [ ]:
# Merge order_data with pincode_mapping to get delivery zone
order_data= pd.merge(order_data, pincode_mapping, on=['Warehouse Pincode','Customer Pincode'])

In [ ]:
#renaming Order_id in order_report
order_report.rename(columns = {'ExternOrderNo':'Order ID'}, inplace = True)

In [ ]:
#Merge order_data with order_report
order_data= pd.merge(order_data, order_report, on='Order ID')

In [ ]:
# Merge merged_order_data with sku_master to get product weights
order_data=pd.merge(order_data,sku_master, on='SKU')

In [ ]:
order_data

,AWB Code,Order ID,Charged Weight,Warehouse Pincode,Customer Pincode,Zone_x,Type of Shipment,Billing Amount (Rs.),Weight Slabs,Forward Fixed Charge,Forward Additional Weight Slab Charge,RTO Fixed Charge,RTO Additional Weight Slab Charge,Zone_y,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),Weight (g)
0,1091117222124,2001806232,1.30,121003,507101,d,Forward charges,140.0,1.25,45.4,44.8,41.3,44.8,d,8904223818645,6,COD,1673,137
1,1091117222124,2001806232,1.30,121003,507101,d,Forward charges,140.0,1.25,45.4,44.8,41.3,44.8,d,8904223819147,2,COD,466,240
2,1091117327312,2001807960,1.00,121003,485001,d,Forward charges,90.2,1.25,45.4,44.8,41.3,44.8,d,8904223819147,1,Prepaid,233,240
3,1091120959225,2001821185,2.10,121003,313001,d,Forward charges,224.6,1.25,45.4,44.8,41.3,44.8,b,8904223819147,1,COD,233,240
4,1091120959225,2001821185,2.10,121003,313001,d,Forward charges,224.6,1.25,45.4,44.8,41.3,44.8,b,8904223819147,1,COD,233,240
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,1091117225484,2001806616,1.08,121003,144001,b,Forward charges,98.6,0.50,33.0,28.3,20.5,28.3,b,8904223819123,1,COD,442,250
563,1091122418320,2001827036,1.60,121003,173213,b,Forward charges,117.9,0.50,33.0,28.3,20.5,28.3,e,8904223819093,1,COD,233,150
564,1091122418320,2001827036,1.60,121003,173213,b,Forward charges,117.9,0.50,33.0,28.3,20.5,28.3,e,8904223819109,1,COD,233,100
565,1091122418320,2001827036,1.60,121003,173213,b,Forward charges,117.9,0.50,33.0,28.3,20.5,28.3,e,GIFTBOX202002,1,COD,659,500
566,1091122418320,2001827036,1.60,121003,173213,b,Forward charges,117.9,0.50,33.0,28.3,20.5,28.3,e,GIFTBOX202002,1,COD,659,500

In [ ]:
#remaing columns name's to easy understand
order_data.rename(columns={'Order Qty':'Order_Qty'},inplace = True)
order_data.rename(columns={'Weight (g)':'Weight'},inplace = True)
order_data.rename(columns={'Item Price(Per Qty.)':'Item_Price'},inplace = True)
order_data.rename(columns={'Billing Amount (Rs.)':'Billing_Amount'},inplace = True)
order_data.rename(columns={'Payment Mode':'Payment_Mode'},inplace = True)

In [ ]:
# Calculate total weight per order based on SKU quantity and gross weight
order_data['Total Weight'] = order_data['Order_Qty'] * order_data['Weight']

In [ ]:
# Calculate expected COD charges
def calculate_cod_charge(payment_Mode, Billing_Amount):
    if payment_Mode == 'COD':
        if Billing_Amount  <= 300:
            return 15
        else:
            return 0.05 * Billing_Amount
    else:
        return 0
order_data['Expected COD Charge'] = order_data.apply(lambda row: calculate_cod_charge(row['Payment_Mode'], row['Billing_Amount']), axis=1)

In [ ]:
def calculate_applicable_weight_slab(Weight, Zone):
    slab_count = order_data[order_data['Zone_x'] == Zone]['Weight Slabs'].values[0]
    return (slab_count + 1) * slab_count
# Calculate the applicable weight slab for each order and add to the order_data DataFrame
order_data['Applicable Weight Slab'] = order_data.apply(lambda row: calculate_applicable_weight_slab(row['Total Weight'], row['Zone_x']), axis=1)

In [ ]:
order_data

,AWB Code,Order ID,Charged Weight,Warehouse Pincode,Customer Pincode,Zone_x,Type of Shipment,Billing_Amount,Weight Slabs,Forward Fixed Charge,...,RTO Additional Weight Slab Charge,Zone_y,SKU,Order_Qty,Payment_Mode,Item_Price,Weight,Total Weight,Expected COD Charge,Applicable Weight Slab
0,1091117222124,2001806232,1.30,121003,507101,d,Forward charges,140.0,1.25,45.4,...,44.8,d,8904223818645,6,COD,1673,137,822,15,2.8125
1,1091117222124,2001806232,1.30,121003,507101,d,Forward charges,140.0,1.25,45.4,...,44.8,d,8904223819147,2,COD,466,240,480,15,2.8125
2,1091117327312,2001807960,1.00,121003,485001,d,Forward charges,90.2,1.25,45.4,...,44.8,d,8904223819147,1,Prepaid,233,240,240,0,2.8125
3,1091120959225,2001821185,2.10,121003,313001,d,Forward charges,224.6,1.25,45.4,...,44.8,b,8904223819147,1,COD,233,240,240,15,2.8125
4,1091120959225,2001821185,2.10,121003,313001,d,Forward charges,224.6,1.25,45.4,...,44.8,b,8904223819147,1,COD,233,240,240,15,2.8125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562,1091117225484,2001806616,1.08,121003,144001,b,Forward charges,98.6,0.50,33.0,...,28.3,b,8904223819123,1,COD,442,250,250,15,0.7500
563,1091122418320,2001827036,1.60,121003,173213,b,Forward charges,117.9,0.50,33.0,...,28.3,e,8904223819093,1,COD,233,150,150,15,0.7500
564,1091122418320,2001827036,1.60,121003,173213,b,Forward charges,117.9,0.50,33.0,...,28.3,e,8904223819109,1,COD,233,100,100,15,0.7500
565,1091122418320,2001827036,1.60,121003,173213,b,Forward charges,117.9,0.50,33.0,...,28.3,e,GIFTBOX202002,1,COD,659,500,500,15,0.7500
566,1091122418320,2001827036,1.60,121003,173213,b,Forward charges,117.9,0.50,33.0,...,28.3,e,GIFTBOX202002,1,COD,659,500,500,15,0.7500

In [ ]:
from pandas.core.dtypes.dtypes import Ordered
# Calculate total forward charge based on weight and zone
def calculate_forward_charge(Weight, Zone):
    rate_row = order_data[(order_data['Zone_x'] == Zone) & (order_data['Forward Fixed Charge'] == 'fwd') & (order_data['Weight Slabs'] == calculate_applicable_weight_slab(Weight, Zone))]
    return order_data['Forward Fixed Charge'].values[0] + (order_data['Forward Additional Weight Slab Charge'].values[0] * (Weight - order_data['Weight Slabs'].values[0]))


order_data['Total Forward Charge'] = order_data.apply(lambda row: calculate_forward_charge(row['Total Weight'], row['Zone_x']), axis=1)

In [ ]:
# Calculate total RTO charge based on weight and zone
def calculate_rto_charge(Weight, Zone):
    rate_row = order_data[(order_data['Zone_x'] == Zone) & (order_data['RTO Fixed Charge'] == 'rto') & (order_data['Weight Slabs'] == calculate_applicable_weight_slab(Weight, Zone))]
    return order_data['RTO Fixed Charge'].values[0] + (order_data['RTO Additional Weight Slab Charge'].values[0] * (Weight - order_data['Weight Slabs'].values[0]))

order_data['Total RTO Charge'] = order_data.apply(lambda row: calculate_rto_charge(row['Total Weight'], row['Zone_x']), axis=1)

In [ ]:
#this gives number of columns and rows
order_data.shape

(124, 29)

In [ ]:
# Calculate total charges
order_data['Total Charges'] = order_data['Total Forward Charge'] + order_data['Total RTO Charge'] + order_data['Expected COD Charge']

In [ ]:
#Looking for the description of the dataset to get insights of the data
order_data.describe()

,AWB Number,Order ID,Total weight as per Courier Company (KG),Warehouse Pincode,Customer Pincode,Charges Billed by Courier Company (Rs.),Weight slab Courier Company (KG),Forward Fixed Charge,Forward Additional Weight Slab Charge,RTO Fixed Charge,...,Weight slab as per X (KG),Total weight as per X (KG),Expected Charge as per X (Rs.),Applicable Weight Slab,Total Forward Charge,Total RTO Charge,Total Charges,Difference,Expected Charges,Charge Difference
count,1.240000e+02,1.240000e+02,124.000000,124.0,124.000000,124.000000,124.000000,124.000000,124.000000,124.000000,...,124.000000,124.000000,124.000000,124.000000,124.000000,124.000000,124.000000,124.000000,124.000000,124.00000
mean,1.091118e+12,2.001811e+09,0.956048,121003.0,365488.072581,112.775806,1.108871,43.180645,41.779032,37.425806,...,168.467742,212.661290,7.137097,2.428427,9516.625806,9512.525806,19036.288710,18923.512903,37952.664516,-37839.88871
std,1.473661e+06,5.167329e+03,0.662815,0.0,152156.322130,64.260301,0.301153,5.203465,6.766324,8.409691,...,100.412032,167.025576,7.521605,0.834033,7482.745784,7482.745784,14965.779656,14937.779388,29903.214512,29875.27062
min,1.091117e+12,2.001806e+09,0.150000,121003.0,140301.000000,33.000000,0.500000,33.000000,28.300000,20.500000,...,65.000000,65.000000,0.000000,0.750000,2901.400000,2897.300000,5798.700000,5751.300000,11550.000000,-197337.00000
25%,1.091117e+12,2.001807e+09,0.667500,121003.0,302017.000000,88.875000,1.250000,45.400000,44.800000,41.300000,...,127.000000,127.000000,0.000000,2.812500,5679.000000,5674.900000,11353.900000,11263.700000,22617.600000,-42720.80000
50%,1.091117e+12,2.001809e+09,0.725000,121003.0,321304.500000,90.200000,1.250000,45.400000,44.800000,41.300000,...,127.000000,127.000000,0.000000,2.812500,5679.000000,5674.900000,11368.900000,11295.100000,22649.000000,-22585.20000
75%,1.091119e+12,2.001812e+09,1.100000,121003.0,405102.250000,135.000000,1.250000,45.400000,44.800000,41.300000,...,210.000000,240.000000,15.000000,2.812500,10741.400000,10737.300000,21478.700000,21366.150000,42844.850000,-22527.40000
max,1.091122e+12,2.001827e+09,4.130000,121003.0,845438.000000,403.800000,1.500000,56.600000,55.500000,50.700000,...,600.000000,1104.000000,15.000000,3.750000,49448.600000,49444.500000,98893.100000,98668.500000,197561.600000,-11487.60000

In [ ]:
#check for count of missing values in each column
order_data.isnull().sum()

AWB Number                                  0
Order ID                                    0
Total weight as per Courier Company (KG)    0
Warehouse Pincode                           0
Customer Pincode                            0
Delivery Zone as per X                      0
Type of Shipment                            0
Charges Billed by Courier Company (Rs.)     0
Weight slab Courier Company (KG)            0
Forward Fixed Charge                        0
Forward Additional Weight Slab Charge       0
RTO Fixed Charge                            0
RTO Additional Weight Slab Charge           0
Delivery Zone charged by Courier Company    0
SKU                                         0
Order_Qty                                   0
Payment_Mode                                0
Item_Price                                  0
Weight slab as per X (KG)                   0
Total weight as per X (KG)                  0
Expected Charge as per X (Rs.)              0
Applicable Weight Slab                      0
Total Forward Charge                        0
Total RTO Charge                            0
Total Charges                               0
Difference                                  0
Expected Charges                            0
Charge Difference                           0
Charge Category                             0
dtype: int64

In [ ]:
#check details about the data set
order_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 124 entries, 0 to 556
Data columns (total 29 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   AWB Number                                124 non-null    int64
 1   Order ID                                  124 non-null    int64
 2   Total weight as per Courier Company (KG)  124 non-null    float64
 3   Warehouse Pincode                         124 non-null    int64
 4   Customer Pincode                          124 non-null    int64
 5   Delivery Zone as per X                    124 non-null    object
 6   Type of Shipment                          124 non-null    object
 7   Charges Billed by Courier Company (Rs.)   124 non-null    float64
 8   Weight slab Courier Company (KG)          124 non-null    float64
 9   Forward Fixed Charge                      124 non-null    float64
 10  Forward Additional Weight Slab Charge     124 non-null    float64
 11  RTO Fixed Charge                          124 non-null    float64
 12  RTO Additional Weight Slab Charge         124 non-null    float64
 13  Delivery Zone charged by Courier Company  124 non-null    object
 14  SKU                                       124 non-null    object
 15  Order_Qty                                 124 non-null    int64
 16  Payment_Mode                              124 non-null    object
 17  Item_Price                                124 non-null    int64
 18  Weight slab as per X (KG)                 124 non-null    int64
 19  Total weight as per X (KG)                124 non-null    int64
 20  Expected Charge as per X (Rs.)            124 non-null    int64
 21  Applicable Weight Slab                    124 non-null    float64
 22  Total Forward Charge                      124 non-null    float64
 23  Total RTO Charge                          124 non-null    float64
 24  Total Charges                             124 non-null    float64
 25  Difference                                124 non-null    float64
 26  Expected Charges                          124 non-null    float64
 27  Charge Difference                         124 non-null    float64
 28  Charge Category                           124 non-null    category
dtypes: category(1), float64(14), int64(9), object(5)
memory usage: 28.3+ KB

In [ ]:

# Calculate the difference between expected charges and billed charges
order_data['Difference'] = order_data['Total Charges'] - order_data['Billing_Amount']

##Output Data 1

In [ ]:
order_data.head(10)

,AWB Number,Order ID,Total weight as per Courier Company (KG),Warehouse Pincode,Customer Pincode,Delivery Zone as per X,Type of Shipment,Charges Billed by Courier Company (Rs.),Weight slab Courier Company (KG),Forward Fixed Charge,...,Total weight as per X (KG),Expected Charge as per X (Rs.),Applicable Weight Slab,Total Forward Charge,Total RTO Charge,Total Charges,Difference,Expected Charges,Charge Difference,Charge Category
0,1091117222124,2001806232,1.30,121003,507101,d,Forward charges,140.0,1.25,45.4,...,822,15,2.8125,36815.0,36810.9,73640.9,73500.9,147126.8,-146986.8,Undercharged
2,1091117327312,2001807960,1.00,121003,485001,d,Forward charges,90.2,1.25,45.4,...,240,0,2.8125,10741.4,10737.3,21478.7,21388.5,42867.2,-42777.0,Undercharged
3,1091120959225,2001821185,2.10,121003,313001,d,Forward charges,224.6,1.25,45.4,...,240,15,2.8125,10741.4,10737.3,21493.7,21269.1,42747.8,-42523.2,Undercharged
7,1091117958163,2001811306,1.10,121003,302017,d,Forward charges,135.0,1.25,45.4,...,240,0,2.8125,10741.4,10737.3,21478.7,21343.7,42822.4,-42687.4,Undercharged
12,1091117333251,2001807613,1.04,121003,335803,d,Forward charges,135.0,1.25,45.4,...,240,15,2.8125,10741.4,10737.3,21493.7,21358.7,42837.4,-42702.4,Undercharged
13,1091120014461,2001818390,0.80,121003,783301,e,Forward and RTO charges,213.5,1.50,56.6,...,240,15,3.7500,10741.4,10737.3,21493.7,21280.2,42758.9,-42545.4,Undercharged
14,1091117222194,2001806273,1.00,121003,486886,d,Forward charges,101.2,1.25,45.4,...,115,15,2.8125,5141.4,5137.3,10293.7,10192.5,20471.2,-20370.0,Undercharged
15,1091117323005,2001807036,1.64,121003,516503,d,Forward charges,179.8,1.25,45.4,...,115,15,2.8125,5141.4,5137.3,10293.7,10113.9,20392.6,-20212.8,Undercharged
16,1091118591534,2001812650,0.61,121003,302002,d,Forward charges,90.2,1.25,45.4,...,115,15,2.8125,5141.4,5137.3,10293.7,10203.5,20482.2,-20392.0,Undercharged
19,1091117323812,2001807186,0.50,121003,396001,d,Forward charges,45.4,1.25,45.4,...,127,0,2.8125,5679.0,5674.9,11353.9,11308.5,22662.4,-22617.0,Undercharged

## Output Data 2

In [ ]:
# Calculate the expected charges for each order
order_data['Expected Charges'] = (
    order_data['Total Forward Charge'] + order_data['Total RTO Charge'] + order_data['Difference']
)

# Compare expected charges with billed charges
order_data['Charge Difference'] = order_data['Billing_Amount'] - order_data['Expected Charges']

# Categorize orders based on charge difference
order_data['Charge Category'] = pd.cut(
    order_data['Charge Difference'],
    bins=[float('-inf'), -0.01, 0.01, float('inf')],
    labels=['Undercharged', 'Correctly Charged', 'Overcharged']
)

# Create the summary table
summary_table = order_data.groupby('Charge Category').agg(
    Count=pd.NamedAgg(column='Order ID', aggfunc='count'),
    Amount=pd.NamedAgg(column='Billing_Amount', aggfunc='sum')
)

# Display the summary table
print(summary_table)

                   Count   Amount
Charge Category
Undercharged         567  69722.3
Correctly Charged      0      0.0
Overcharged            0      0.0

In [306]:
summary_table.to_csv('output2.csv')

In [ ]:
order_data.drop_duplicates('AWB Code',inplace=True)

In [ ]:
#remaining as per your request
order_data.rename(columns={'AWB Code':'AWB Number'},inplace = True)
order_data.rename(columns={'Total Weight':'Total weight as per X (KG)'},inplace = True)
order_data.rename(columns={'Weight':'Weight slab as per X (KG)'},inplace = True)
order_data.rename(columns={'Charged Weight':'Total weight as per Courier Company (KG)'},inplace = True)
order_data.rename(columns={'Weight Slabs':'Weight slab Courier Company (KG)'},inplace = True)
order_data.rename(columns={'Zone_x':'Delivery Zone as per X'},inplace = True)
order_data.rename(columns={'Zone_y':'Delivery Zone charged by Courier Company'},inplace = True)
order_data.rename(columns={'Expected COD Charge':'Expected Charge as per X (Rs.)'},inplace = True)
order_data.rename(columns={'Billing_Amount':'Charges Billed by Courier Company (Rs.) '},inplace = True)

In [ ]:
#redusing data set because in showing columns limit is 20
order_data.drop(['Warehouse Pincode','Customer Pincode','Type of Shipment','Payment_Mode','SKU','Item_Price'],axis=1)

,AWB Number,Order ID,Total weight as per Courier Company (KG),Delivery Zone as per X,Charges Billed by Courier Company (Rs.),Weight slab Courier Company (KG),Forward Fixed Charge,Forward Additional Weight Slab Charge,RTO Fixed Charge,RTO Additional Weight Slab Charge,...,Total weight as per X (KG),Expected Charge as per X (Rs.),Applicable Weight Slab,Total Forward Charge,Total RTO Charge,Total Charges,Difference,Expected Charges,Charge Difference,Charge Category
0,1091117222124,2001806232,1.30,d,140.0,1.25,45.4,44.8,41.3,44.8,...,822,15,2.8125,36815.0,36810.9,73640.9,73500.9,147126.8,-146986.8,Undercharged
2,1091117327312,2001807960,1.00,d,90.2,1.25,45.4,44.8,41.3,44.8,...,240,0,2.8125,10741.4,10737.3,21478.7,21388.5,42867.2,-42777.0,Undercharged
3,1091120959225,2001821185,2.10,d,224.6,1.25,45.4,44.8,41.3,44.8,...,240,15,2.8125,10741.4,10737.3,21493.7,21269.1,42747.8,-42523.2,Undercharged
7,1091117958163,2001811306,1.10,d,135.0,1.25,45.4,44.8,41.3,44.8,...,240,0,2.8125,10741.4,10737.3,21478.7,21343.7,42822.4,-42687.4,Undercharged
12,1091117333251,2001807613,1.04,d,135.0,1.25,45.4,44.8,41.3,44.8,...,240,15,2.8125,10741.4,10737.3,21493.7,21358.7,42837.4,-42702.4,Undercharged
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,1091117435134,2001808118,0.50,b,33.0,0.50,33.0,28.3,20.5,28.3,...,65,0,0.7500,2901.4,2897.3,5798.7,5765.7,11564.4,-11531.4,Undercharged
507,1091117437050,2001808675,1.20,b,89.6,0.50,33.0,28.3,20.5,28.3,...,113,15,0.7500,5051.8,5047.7,10114.5,10024.9,20124.4,-20034.8,Undercharged
510,1091117958395,2001811363,0.59,d,90.2,1.25,45.4,44.8,41.3,44.8,...,165,0,2.8125,7381.4,7377.3,14758.7,14668.5,29427.2,-29337.0,Undercharged
512,1091120922803,2001820978,0.50,d,45.4,1.25,45.4,44.8,41.3,44.8,...,165,0,2.8125,7381.4,7377.3,14758.7,14713.3,29472.0,-29426.6,Undercharged
556,1091117324346,2001807328,2.28,d,235.6,1.25,45.4,44.8,41.3,44.8,...,490,15,2.8125,21941.4,21937.3,43893.7,43658.1,87536.8,-87301.2,Undercharged

In [ ]:
selected_columns = ['Order ID', 'AWB Number', 'Total weight as per Courier Company (KG)', 'Delivery Zone as per X', 'Weight slab Courier Company (KG)', 'Total weight as per X (KG)', 'Expected Charge as per X (Rs.)', 'Expected Charge as per X (Rs.)', 'Difference']

new_data_frame = order_data[selected_columns]

In [ ]:
new_data_frame

,Order ID,AWB Number,Total weight as per Courier Company (KG),Delivery Zone as per X,Weight slab Courier Company (KG),Total weight as per X (KG),Expected Charge as per X (Rs.),Expected Charge as per X (Rs.),Difference
0,2001806232,1091117222124,1.30,d,1.25,822,15,15,73500.9
2,2001807960,1091117327312,1.00,d,1.25,240,0,0,21388.5
3,2001821185,1091120959225,2.10,d,1.25,240,15,15,21269.1
7,2001811306,1091117958163,1.10,d,1.25,240,0,0,21343.7
12,2001807613,1091117333251,1.04,d,1.25,240,15,15,21358.7
...,...,...,...,...,...,...,...,...,...
503,2001808118,1091117435134,0.50,b,0.50,65,0,0,5765.7
507,2001808675,1091117437050,1.20,b,0.50,113,15,15,10024.9
510,2001811363,1091117958395,0.59,d,1.25,165,0,0,14668.5
512,2001820978,1091120922803,0.50,d,1.25,165,0,0,14713.3
556,2001807328,1091117324346,2.28,d,1.25,490,15,15,43658.1

In [ ]:
order_data.to_csv('new_assignment.csv', index=False)